name: omnitrack
description: OmniTrack - A Flutter app for real-time bus tracking system with admin and user interfaces.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  http: ^1.2.2  # Required for HTTP requests
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.6.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: []